version: '3.7'

services:

  ors-client-service:
    container_name: ors-admin-client
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true