const shopData = [
  {
    id: '1',
    name: 'OIL/BNB LP',
    image: '/images/logo/busd.png',
    bgImage: '/images/logo/busd.svg',
    description: 'BUSD/USDT/USDC/DAI',
    balance: '$0.00',
    deposited: '$0.00',
    apy: '0.00%',
    daily: '0.00%',
    tvl: '$0.00M',
    reward: '$0.00',
    inactive: false,
    paused: false,
    boosted: true
  },
  {
    id: '2',
    name: 'DIESEL/BNB LP',
    image: '/images/logo/cake.svg',
    bgImage: '/images/logo/pancake.svg',
    description: 'CAKE-BNB LP',
    balance: '$0.00',
    deposited: '$0.00',
    apy: '0.00%',
    daily: '0.00%',
    tvl: '$0.00M',
    reward: '$0.00',
    inactive: false,
    paused: false,
    boosted: true
  },
  {
    id: '3',
    name: 'OIL',
    image: '/images/logo/oil.svg',
    bgImage: '/images/logo/pancake.svg',
    description: 'AUTO_BNG LP',
    balance: '$0.00',
    deposited: '$0.00',
    apy: '0.00%',
    daily: '0.00%',
    tvl: '$0.00M',
    reward: '$0.00',
    inactive: false,
    paused: false,
    boosted: false
  },
  {
    id: '4',
    name: 'DIESEL',
    image: '/images/logo/diesel.svg',
    bgImage: '/images/logo/pancake.svg',
    description: 'BITI-BNB LP',
    balance: '$0.00',
    deposited: '$0.00',
    apy: '0.00%',
    daily: '0.00%',
    tvl: '$0.00M',
    reward: '$0.00',
    inactive: false,
    paused: false,
    boosted: false
  },
  {
    id: '5',
    name: 'BNB',
    image: '/images/logo/bnb.svg',
    bgImage: '/images/logo/venus.svg',
    description: 'PALM-BUSD LP',
    balance: '$0.00',
    deposited: '$0.00',
    apy: '0.00%',
    daily: '0.00%',
    tvl: '$0.00M',
    reward: '$0.00',
    inactive: false,
    paused: false,
    boosted: false
  },
  {
    id: '6',
    name: 'BUSD',
    image: '/images/logo/busd.svg',
    bgImage: '/images/logo/venus.svg',
    description: 'PALM-BNB LP',
    balance: '$0.00',
    deposited: '$0.00',
    apy: '0.00%',
    daily: '0.00%',
    tvl: '$0.00M',
    reward: '$0.00',
    inactive: false,
    paused: false,
    boosted: false
  },
  {
    id: '7',
    name: 'USDT',
    image: '/images/logo/tusd.svg',
    bgImage: '/images/logo/venus.svg',
    description: 'CAKE',
    balance: '$0.00',
    deposited: '$0.00',
    apy: '0.00%',
    daily: '0.00%',
    tvl: '$0.00M',
    reward: '$0.00',
    inactive: true,
    paused: false,
    boosted: false
  },
  {
    id: '8',
    name: 'ETH',
    image: '/images/logo/eth.svg',
    bgImage: '/images/logo/venus.svg',
    description: 'SWAMP',
    balance: '$0.00',
    deposited: '$0.00',
    apy: '0.00%',
    daily: '0.00%',
    tvl: '$0.00M',
    reward: '$0.00',
    inactive: false,
    paused: false,
    boosted: false
  },
  {
    id: '9',
    name: 'BTC',
    image: '/images/logo/btc.svg',
    bgImage: '/images/logo/venus.svg',
    description: 'SWAMP',
    balance: '$0.00',
    deposited: '$0.00',
    apy: '0.00%',
    daily: '0.00%',
    tvl: '$0.00M',
    reward: '$0.00',
    inactive: false,
    paused: false,
    boosted: false
  },
  {
    id: '10',
    name: 'CAKE',
    image: '/images/logo/cake.svg',
    bgImage: '/images/logo/pancake.svg',
    description: 'SWAMP',
    balance: '$0.00',
    deposited: '$0.00',
    apy: '0.00%',
    daily: '0.00%',
    tvl: '$0.00M',
    reward: '$0.00',
    inactive: false,
    paused: false,
    boosted: false
  },
  // {
  //   id: '11',
  //   name: 'HPS',
  //   image: '/images/dummy/hps.svg',
  //   bgImage: '/images/logo/julswap.svg',
  //   description: 'SWAMP',
  //   balance: '$0.00',
  //   deposited: '$0.00',
  //   apy: '0.00%',
  //   daily: '0.00%',
  //   tvl: '$0.00M',
  //   reward: '$0.00',
  //   inactive: false,
  //   paused: true,
  //   boosted: false
  // },
  // {
  //   id: '12',
  //   name: 'HPS/BNB LP',
  //   image: '/images/dummy/swamp.svg',
  //   bgImage: '/images/logo/julswap.svg',
  //   description: 'SWAMP',
  //   balance: '$0.00',
  //   deposited: '$0.00',
  //   apy: '0.00%',
  //   daily: '0.00%',
  //   tvl: '$0.00M',
  //   reward: '$0.00',
  //   inactive: false,
  //   paused: true,
  //   boosted: false
  // }
];

export default shopData;
